### PR TITLE
Add an option to show/hide empty monster card

### PR DESCRIPTION
**Pull request by minchik**

### CODE REVIEW

**Comment by ciotlosm** [comment]
>

@minchik does it show again once entities state changes to get again entities in the list?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by minchik** [comment]
Sorry my fault. Not properly understood how Lovelace ui works.

**Comment by ciotlosm** [comment]
>Sorry my fault. Not properly understood how Lovelace ui works.

@minchik no worries. I really appreciate contributions. I think it just need one more change. Default for the new setting should be to keep current behavior. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by minchik** [comment]
Do you think most people want to see empty cards instead of hiding it? If yes I'll change it))

**Comment by ciotlosm** [comment]
It depends. If you hide it, flow of columns might change. Depends on people, but I would assume people would want to avoid unexpected behaviour

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by minchik** [comment]
Changing number of entities in the card by applying filters will change card height and can change columns flow anyway. So I think this is expected behaviour. Anyway I'll change it to sync monster-card and entity-filter card behaviour

**Pull request merged**
